### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by Yerprog** [tripflex/wp-job-manager-registration-use-email#4]
Hi, do you know or is it possible to make some kind of email verification for job manager registration?
at the time new user just fills email and password, choses the role and thats it.

verification Email not sending to user. Password is already given to him. Pls help to find such option or you could implement it, as you are familiar with the wp job manager registration! Thanks!

**Comment by tripflex** [comment]
This is no longer a problem with WordPress 4.3 as starting with 4.3 the user is emailed a link to set their password, which in essence becomes an email verification process.
