### ISSUE TITLE
Email fields doubled in the Jobify sign-up modal

### ISSUE THREAD

**Issue by sazemaster** [tripflex/wp-job-manager-registration-use-email#6]
Hello

In the Jobify theme when this plugin is enabled, the Sign-up modal to register a new user shows two e-mail fields: "Username or Email" and "Email address" just below.

This situation creates a confusion point for the end-user.

I believe a solution would be for the plugin to **ask only for the e-mail address**, getting rid of the username option because an e-mail is needed anyway to contact the users in a job-board system like wpjm.

![screen shot 2015-06-04 at 11 12 55](https://cloud.githubusercontent.com/assets/5401925/7980802/c4d3756a-0aaa-11e5-92f4-2e188a144da3.png)

Cheers
Luca

**Comment by tripflex** [comment]
I think you could use the filter to remove it from the jobify register form:

```php
add_filter('register_form_fields', 'remove_jobify_register_username');

function remove_jobify_register_username( $fields ){
    if( isset( $fields['nicename'] ) ) unset( $fields['nicename'] );
    return $fields;
}
```

I'll look at possibly adding a check if the theme is Jobify and removing this field if it is ...  but in the meantime you can add that code to your `functions.php` file for your child theme and it *should* work

**Comment by sazemaster** [comment]
Hi @tripflex 

I tried the suggested filter but the theme still displays both fields.
Any suggestion? Can I help in some way?

Cheers
Luca

**Comment by tripflex** [comment]
Whoops I missed that it was an array of an array, i've updated the code above and it should work now

**Comment by contractorcloud** [comment]
Hi @tripflex 

Thanks!!! Worked perfectly :)

**Comment by sazemaster** [comment]
Unfortunately I can't get it to work yet. I found [this post](https://wordpress.org/support/topic/how-to-add-custom-field-to-wordpress-register-form?replies=6#post-7110474) if it can help. Thanks

**Comment by contractorcloud** [comment]
Worked great for me, thanks @tripflex

**Comment by sazemaster** [comment]
Thanks @tripflex, the updated code makes the nicename field disappear but now users can't get created and there is a notice at the top of the page:

> Notice: Undefined index: nicename in /home/content/p3pnexwpnas07_data03/90/2632890/html/wp-content/themes/jobify/inc/integrations/wp-job-manager/wp-job-manager-form-register.php on line 464

Code responsible for that notice:
```PHP
    $username = sanitize_user( $values[ 'nicename' ] );
```

**Comment by tripflex** [comment]
Okay let me test on a jobify demo and I'll let you guys know

**Comment by sazemaster** [comment]
Hi @tripflex do you have any news on this? :) I think quite a few people would love to see this working!
Thanks for your help!

**Comment by tripflex** [comment]
Sorry been busy after taking a trip to NC mountains to go hiking.  I'll test it out today and let you know

**Comment by tripflex** [comment]
Fixed in 1.3.0

**Comment by sazemaster** [comment]
Good job! I'll test and in case I'll let you know if I find any issue.
Thanks @tripflex :)

**Comment by tidus291** [comment]
Hi, what's name plugin that use sazemaster ??? I need it.
